def show_menu():
    print("==================================================")
    print("SECURE CRYPTOGRAPHY SYSTEM")
    print("==================================================")
    print("1. Initialize system (generate keys & certificates)")
    print("2. Establish shared key (DH exchange with authentication)")
    print("3. Encrypt a message (A -> B)")
    print("4. Decrypt a message (B)")
    print("5. Show current status")
    print("6. Exit")
    print("==================================================")